name: hello-world

on:
  push:
  workflow_dispatch:

jobs:
  standard:
    runs-on: ubuntu-latest
    steps:
      - name: Debug
        run: |
          echo "Hello world"
          echo "${{ github.event.repository.name }}; ${{ github.ref_name }}; ${{ github.ref_type }}"

