name: hello-world

on:
  workflow_dispatch:
    inputs:
      git-ref:
        description: 'Branch, tag or SHA to checkout'
        required: true
        default: 'main'
  push:
    tags:
      - '*'

jobs:
  standard:
    runs-on: ubuntu-latest
    steps:
      - name: Debug
        shell: bash
        run: |
          echo "${{ toJson(github.event) }}"
          echo "${{ github.event_name }}"
          echo "${{ github.ref_type }}"
          echo "${{ github.event.repository.name }}"
          echo "Hello world"
          echo "`basename ${{ github.repository }}`; ${{ github.ref_name }}; ${{ github.ref_type }}"
      - name: Condition
        if: |
          github.event_name == 'workflow_dispatch' &&
          contains(github.ref_type, 'ta')
        shell: bash
        run: |
          echo "Match"
          exit 1
