name: hello-world

on:
  push:
  workflow_dispatch:

jobs:
  standard:
    runs-on: ubuntu-latest
    steps:
      - name: Debug
        run: |
          echo "${{ toJson(github.event) }}"
          echo "${{ github.event.repository.name }}"
          echo "Hello world"
          echo "`basename ${{ github.repository }}`; ${{ github.ref_name }}; ${{ github.ref_type }}"

