name: src-mirror

on:
  workflow_dispatch:
    inputs:
      git-ref:
        description: 'Branch, tag or SHA to checkout'
        required: true
        default: 'main'
  push:
    tags:
      - '*'
  pull_request:
    types:
      - opened
      - synchronize
    paths:
      - .github/workflows/src-mirror.yml

concurrency:
  group: src-mirror-${{ github.ref }}
  cancel-in-progress: true

jobs:
  standard:
    runs-on: ubuntu-latest
    steps:
      - name: Upload src.tar.gz
        uses: datgizmo/action-src-mirror@add-release-bundle-creation
        with:
          path: 'nrf-bm'
          west-update-args: ''
          artifactory-path: >-
            ${{ (github.ref_type != 'tag') &&
              format('generic-local/internal/{0}/{1}/src.tar.gz', github.event.repository.name, github.ref_name) ||
              format('generic-local/external/{0}/{1}/src.tar.gz', github.event.repository.name, github.ref_name) }}
          artifactory-user: ${{ secrets.COM_NORDICSEMI_FILES_USERNAME }}
          artifactory-pass: ${{ secrets.COM_NORDICSEMI_FILES_PASSWORD }}
